export const FETCH_CONTACTS = "FETCH_CONTACTS";
export const RECEIVE_CONTACTS = "RECEIVE_CONTACTS";
export const ALPHABETICAL_CONTACTS = "ALPHABETICAL_CONTACTS";
export const RECEIVE_CHOOSEN_CHAR = "RECEIVE_CHOOSEN_CHAR";
export const SET_ACTIVE_CARD = "SET_ACTIVE_CARD";
export const RETRIEVE_ACTIVE_CARD_EMAIL = "RETRIEVE_ACTIVE_CARD_EMAIL";
export const RETRIEVE_CONTACTS_BY_CHAR = "RETRIEVE_CONTACTS_BY_CHAR";
